"""creacion de la tabla de platos

Revision ID: ee17b99c00a1
Revises: 2257c8499b14
Create Date: 2026-09-18 14:51:15.386071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee17b99c00a1'
down_revision = '2257c8499b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('platos', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platos')
    # ### end Alembic commands ###
